### PR TITLE
adding iso-8859-1 compatiblity to get special char compatiblity like éèàç

### PR DESCRIPTION
**Pull request by Onion2222**
This merge will add iso-8859-1 decoding compatibly to get characters like "éèàç" displayed correctly

### CODE REVIEW

**Comment by abulgher** [comment]
Hi @Onion2222 , I have a similar problem as yours (I have opened an issue #35), when posting a message containing special accented characters like èéà are wrongly encoded resulting in funny characters when displayed. 

Have you also experienced something like this?

**Comment by Onion2222** [comment]
> Hi @Onion2222 , I have a similar problem as yours (I have opened an issue #35), when posting a message containing special accented characters like èéà are wrongly encoded resulting in funny characters when displayed.
> 
> Have you also experienced something like this?

I didn't try to post a message. Maybe the fix is similar. 
I think you have to modify the regex in the private method `_replace_special_characters_in_attribute_key` to include accented characters. But I didn't try.

**Comment by abulgher** [comment]
> @abulgher
> 
> > Hi @Onion2222 , I have a similar problem as yours (I have opened an issue #35), when posting a message containing special accented characters like èéà are wrongly encoded resulting in funny characters when displayed.
> > Have you also experienced something like this?
> 
> I didn't try to post a message. Maybe the fix is similar. I think you have to modify the regex in the private method `_replace_special_characters_in_attribute_key` to include accented characters. But I didn't try.

Actually I think the method you suggested is only doing some replacements in attribute keys and not values. I will have another look in the code and hopefully come up with a pull request.

**Comment by abulgher** [comment]
@Onion2222 have a look at PR #36. It should implement your 'read back' along with the possibility to post messages and attributes with special characters.

**Comment by simongregorebner** [comment]
closing this one as the necessary changes are as well in #36

**Pull request closed without merging**
