### PR TITLE
Added the build_python_package and the publish_python_package

### PR DESCRIPTION
**Pull request by abulgher**
I could not find the elog package on PyPI and this was preventing the installation via a simple pip install. 

In order to accomplish this I made the following changes:

1. Package name renamed to py_elog because elog was already taken in PyPI
2. Recoded a bit the test suit to make use of the Linux+Demo elog because public accessible. 
3. Added the workflow to create a package and to publish it.
4. Created a new tag 1.3.12 in order to have this new code available in the released package.

If you decide to merge this pull request:
1. I will gladly transfer the ownership of the project of PyPI
2. You will have to adjust the security tokens accordingly.

### CODE REVIEW

**Comment by simongregorebner** [comment]
@abulgher Sorry for the late reply and thanks a lot for this pull request!
It would be great if you could transfer the ownership of the py_elog package on pypi to us (username: paulscherrerinstitute). As soon as this is done I can setup the publish token then

**Comment by abulgher** [comment]
I'm on vacation right now with limited internet access. I'll do it as soon
as I am back.

Thanks

Il gio 21 lug 2022, 11:20 Simon Gregor Ebner ***@***.***> ha
scritto:

**Comment by simongregorebner** [comment]
great thanks!

**Comment by abulgher** [comment]
Hello there!

I have added your username to the collaborator list with owner role. I
think you will be able to remove me as soon as you accept the invitation.

Cheers!

**Comment by abulgher** [comment]
Hi! I'm still waiting you to accept the invitation on pypi. did I do something wrong?

**Comment by simongregorebner** [comment]
@abulgher Sorry for the late reply, I was on holidays the last weeks and wasn't paying attention to my business emails. Could you send me an invitation again? (apparently the invites you sent expired)

**Comment by abulgher** [comment]
Just sent it again now 
:)

**Comment by simongregorebner** [comment]
now it worked =) , thanks!
(It will probably take me some days before I continue working on this - still have to go through tons of emails)

**Comment by abulgher** [comment]
No worries! take it easy, we all know how a mail box can look after vacation. 
You can downgrade me or even remove me from the package later on.

**Pull request merged**
